[env.development]
TARGET_PATH = "./target/x86_64-pc-windows-msvc/debug"

[env.release]
TARGET_PATH = "./target/x86_64-pc-windows-msvc/release"
BUILD_FLAGS = "--release"

[tasks.build-driver]
script = [
    "cargo b %BUILD_FLAGS%"
]

[tasks.rename]
ignore_errors = true
script = [
    "cd %TARGET_PATH%",
    "del valthrun-driver.sys",
    "ren driver.dll valthrun-driver.sys",
]

[tasks.sign]
dependencies = ["build-driver", "rename"]
script = [
    "Powershell.exe -File Sign-Driver.ps1 %TARGET_PATH%/valthrun-driver.sys"
]