[package]
name = "utils-imports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { version = "1.0", package = "thiserror-core", default-features = false }
once_cell = { version = "1.18.0", default-features = false, features = ["alloc"] }
obfstr = "0.4.3"
paste = "1.0.14"

[dependencies.winapi]
git = "https://github.com/Trantect/winapi-rs.git"
branch = "feature/km"
features = [
    "wdm",
    "ntstatus",
    "impl-default"
]
