
[build]
target = "x86_64-pc-windows-msvc"
rustflags = [
    # Compile settings
    # "-C", "force-unwind-tables=false",
    # "-C", "build-std-features=panic_immediate_abort",
    # "-C", "llvm-args='-fno-unwind-tables'",

    # Pre Link Args
    "-Z",
    "pre-link-arg=/NOLOGO",
    "-Z",
    "pre-link-arg=/NXCOMPAT",
    "-Z",
    "pre-link-arg=/NODEFAULTLIB",
    "-Z",
    "pre-link-arg=/SUBSYSTEM:NATIVE",
    "-Z",
    "pre-link-arg=/DRIVER",
    "-Z",
    "pre-link-arg=/DYNAMICBASE",
    "-Z",
    "pre-link-arg=/MANIFEST:NO",

    # "-Z", "pre-link-arg=/PDBALTPATH:https://youtu.be/dQw4w9WgXcQ",

    # Post Link Args
    "-C",
    "link-arg=/OPT:REF,ICF",
    "-C",
    "link-arg=/ENTRY:driver_entry",
    "-C",
    "link-arg=/MERGE:.btext=.text",
    "-C",
    "link-arg=/MERGE:.edata=.rdata",
    "-C",
    "link-arg=/MERGE:.rustc=.data",
    "-C",
    "link-arg=/INTEGRITYCHECK",

]
