name: Rust

on:
  push:
    branches: ["master", "uefi"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-12-26
          target: x86_64-unknown-uefi
          components: rustfmt
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
      - name: Check fmt
        run: cargo fmt --check

      - name: Build Driver
        run: ./.github/workflows/build-driver.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: valthrun-driver-standalone
          path: |
            target/x86_64-pc-windows-msvc/release/valthrun-driver.sys
            target/x86_64-pc-windows-msvc/release/driver_standalone.pdb

      - name: Build UEFI Driver
        run: ./.github/workflows/build-driver-uefi.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: valthrun-driver-uefi
          path: |
            target/x86_64-pc-windows-msvc/release/driver_uefi.dll
            target/x86_64-pc-windows-msvc/release/driver_uefi.pdb
