name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Check fmt
      run: rustup component add rustfmt && cargo fmt --check
    - name: Setup WDK
      run: .github/workflows/Install-WDK.ps1
    - name: Build
      run: cargo make --profile=release sign
    # Right now there are no tests specified
    # - name: Run tests
    #   run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: valthrun-driver
        path: target/x86_64-pc-windows-msvc/release/valthrun-driver.sys